apiVersion: batch/v1
kind: Job
metadata:
  name: db-seeder
spec:
  template:
    spec:
      containers:
        - name: seeder
          image: {{ (index .Values "percona-xtradb-cluster").image.repository }}:{{ (index .Values "percona-xtradb-cluster").image.tag }}
          env:
            - name: DATABASE_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pxc
                  key: mysql-root-password
            - name: DATABASE_HOST
              value: {{ .Release.Name }}-pxc
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: CLOUD_CONTROLLER_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}.var-cc-database-password
                  key: password
            - name: DIEGO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}.var-diego-database-password
                  key: password
            - name: NETWORK_CONNECTIVITY_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}.var-network-connectivity-database-password
                  key: password
            - name: NETWORK_POLICY_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}.var-network-policy-database-password
                  key: password
            - name: ROUTING_API_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}.var-routing-api-database-password
                  key: password
            - name: UAA_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}.var-uaa-database-password
                  key: password
            - name: LOCKET_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}.var-locket-database-password
                  key: password
            - name: CREDHUB_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}.var-credhub-database-password
                  key: password
          command:
            - "/bin/bash"
            - "-ce"
            - |
              echo "Starting seeding..."
              databases=(
                "cloud_controller"
                "diego"
                "network_connectivity"
                "network_policy"
                "routing-api"
                "uaa"
                "locket"
                "credhub"
              )

              until echo "SELECT 'Ready!'" | mysql --host="${DATABASE_HOST}.${NAMESPACE}.svc" --user=root --password="${DATABASE_ROOT_PASSWORD}"; do
                echo "database not ready.."
                sleep 1
              done


              mysql --host="${DATABASE_HOST}.${NAMESPACE}.svc" --user=root --password="${DATABASE_ROOT_PASSWORD}" \
              < <(
                for database in ${databases[*]}; do
                  password_var="${database//-/_}_DATABASE_PASSWORD"
                  password_var="${password_var^^}"

                  echo "CREATE USER \`${database}\` IDENTIFIED BY '${!password_var}';"
                  echo "CREATE DATABASE IF NOT EXISTS \`${database}\`;"
                  echo "GRANT ALL ON \`${database}\`.* TO '${database}'@'%';"
                done
              )
              echo "done."
      restartPolicy: Never
